
TesterAutoescuela.class: TesterAutoescuela.java Persona.java Fecha.java
	javac Fecha.java Persona.java TesterAutoescuela.java

Fecha.class: Fecha.java
	javac Fecha.java

Persona.class: Persona.java
	javac Persona.java

clean:
	rm -rf *.class

doc:
	javadoc -d doc Fecha.java Persona.java

