Test.class: Test.java Persona.java Fecha.java Autoescuela.java
	javac Fecha.java Persona.java Test.java Autoescuela.java

Autoescuela.class:
	javac Autoescuela.java

Fecha.class: Fecha.java
	javac Fecha.java

Persona.class: Persona.java
	javac Persona.java

clean:
	rm -rf *.class

doc:
	javadoc -d doc Fecha.java Autoescuela.java Persona.java
