##Victoria Pelayo e Ignacio Rabunnal
##
## Para ejecutar programa tartaglia escribir en terminal:
## java Tartaglia n
## sustituyendo n por el numero de lineas

all: Combinatoria.class Tartaglia.class

clean:
	rm -rf *.class

Tartaglia.class: Tartaglia.java
	javac Tartaglia.java

Combinatoria.class: Combinatoria.java
	javac Combinatoria.java


